--!strict

return table.freeze({
	Click = table.freeze({ Start = 0.200, Length = 0.090, Looped = false }),
	Open = table.freeze({ Start = 0.800, Length = 0.639, Looped = false }),
	Purchase = table.freeze({ Start = 2.000, Length = 1.871, Looped = false }),
	Cash = table.freeze({ Start = 4.400, Length = 1.525, Looped = false }),
	Perfect = table.freeze({ Start = 6.500, Length = 2.120, Looped = false }),
	Launch = table.freeze({ Start = 9.200, Length = 1.900, Looped = false }),
	Land = table.freeze({ Start = 11.600, Length = 0.997, Looped = false }),
	Zone = table.freeze({ Start = 13.100, Length = 2.934, Looped = false }),
	Error = table.freeze({ Start = 16.600, Length = 0.265, Looped = false }),
	Rebirth = table.freeze({ Start = 17.400, Length = 4.376, Looped = false }),
	Swoosh = table.freeze({ Start = 22.300, Length = 0.773, Looped = false }),
	Boost = table.freeze({ Start = 23.600, Length = 2.000, Looped = true }),
	Wind = table.freeze({ Start = 26.100, Length = 4.000, Looped = true }),
})
